# Numpy Foundation

In [ ]:
# !pip install numpy==version pandas seaborn == verssion

5


In [62]:
import numpy as np

In [63]:
temps = np.array([22,24,18,21,23,25,26])

In [64]:
type(temps)

numpy.ndarray

In [65]:
temps.ndim

1

In [66]:
temps.size

7

In [67]:
temps.shape

(7,)

In [68]:
temps.dtype

dtype('int64')

In [69]:
temps = np.array([22.5,24,18,21,23,25,26])

In [70]:
temps.dtype

dtype('float64')

## 2-D arrays

In [71]:
grid  = np.array([[22,24,19,21,23,25,26],
                         [21,24,24,21,23,25,27],
                         [28,29,27,28,31,33,30]
                         ]
                    )

In [72]:
grid.shape

(3, 7)

In [73]:
grid.ndim

2

## Creating arrays without values

In [74]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(2)

array([1., 1.])

In [17]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
list(range(0,9,2))

[0, 2, 4, 6, 8]

In [21]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## Reshaping: the same data, a different layout
reshaping doesn't change the values or copy them -- it changes how the same block of memory is viewed.

In [26]:
flat = np.arange(1,22)

In [27]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [28]:
flat.shape

(21,)

In [31]:
k = flat.reshape(3,7)

In [32]:
k

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [33]:
flat.size

21

In [34]:
k.size

21

In [35]:
k.ndim

2

In [ ]:
k.shape

(3, 7)

In [ ]:
# if you dont know the the how to reshape
flat.reshape(3, -1)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [ ]:
# 1,12: 1-D array; reshape to 3*4 matrix

In [46]:
flat = np.arange(1,13)
print(flat)
k = flat.reshape(3,4)
print(k)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
# if we want to back the 2 d to first 1 d then use flatten
k.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
k.shape


(3, 4)

In [55]:
k.ndim

2

In [75]:
temps[-1]

np.float64(26.0)

In [76]:
# reverse
temps[::-1]

array([26. , 25. , 23. , 21. , 18. , 24. , 22.5])

In [77]:
temps[:2]

array([22.5, 24. ])

## slicing a 2D gird

In [78]:
grid[0:1]

array([[22, 24, 19, 21, 23, 25, 26]])

In [ ]:
# temperature of all cities for moday and tuesday: monday -> sunday:moday -> index 0 and sunday -> index 6
grid[:, 0:2]


array([[22, 24],
       [21, 24],
       [28, 29]])

In [82]:
grid

array([[22, 24, 19, 21, 23, 25, 26],
       [21, 24, 24, 21, 23, 25, 27],
       [28, 29, 27, 28, 31, 33, 30]])

In [ ]:
# temperature greater than 25
grid > 25 # This execute to all the temperature in grid

array([[False, False, False, False, False, False,  True],
       [False, False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [84]:
grid[grid>25]

array([26, 27, 28, 29, 27, 28, 31, 33, 30])

## Views vs. copies: what slicing actually returns

In [ ]:
first_three = temps[0:3]
first_three[0] = 100
print(temps) # changed too

[100.  24.  18.  21.  23.  25.  26.]


In [86]:
temps = np.array([22,24,18,21,23,25,26])

In [ ]:
# for data manipulation do copy
safe_copy = temps[0:3].copy()  # now independent

In [88]:
safe_copy[0] = 100

In [89]:
print(temps)
print(safe_copy)

[22 24 18 21 23 25 26]
[100  24  18]


## vectorized operation

In [90]:
# The loop way 
fahrenheit = []
for c in temps:
    fahrenheit.append(c * 9/5 + 32)

In [ ]:
# the vectorized way
fahrenheit = c * 9/5 + 32
# it does element - wise arithmetic

## Builts in functions

In [92]:
np.sqrt(temps)

array([4.69041576, 4.89897949, 4.24264069, 4.58257569, 4.79583152,
       5.        , 5.09901951])

In [93]:
np.round(temps / 3, 1)

array([7.3, 8. , 6. , 7. , 7.7, 8.3, 8.7])

# Broadcasting

In [95]:
grid

array([[22, 24, 19, 21, 23, 25, 26],
       [21, 24, 24, 21, 23, 25, 27],
       [28, 29, 27, 28, 31, 33, 30]])

In [94]:
city_avg = grid.mean(axis = 1, keepdims=True)
print(city_avg)

[[22.85714286]
 [23.57142857]
 [29.42857143]]


In [96]:
city_avg.shape

(3, 1)

In [97]:
differnece = grid - city_avg
print(differnece)

[[-0.85714286  1.14285714 -3.85714286 -1.85714286  0.14285714  2.14285714
   3.14285714]
 [-2.57142857  0.42857143  0.42857143 -2.57142857 -0.57142857  1.42857143
   3.42857143]
 [-1.42857143 -0.42857143 -2.42857143 -1.42857143  1.57142857  3.57142857
   0.57142857]]


In [98]:
differnece.shape

(3, 7)

## Matrix multiplication

In [99]:
a = np.array([2,3,1])
b = np.array([10,10,10])

In [ ]:
a * b # element wise multiplication

array([20, 30, 10])

In [ ]:
# dot product
a @ b

np.int64(60)

In [102]:
np.dot(a,b)

np.int64(60)

## Aggregating along an axis
axis = 0 walks down the rows(collapses cities, keeps 7 days in grid)
axis = 1 walks acorss the columns(collapses days, keeps 3 cities)

In [104]:
grid.sum(axis = 0)

array([71, 77, 70, 70, 77, 83, 83])

In [105]:
grid.sum(axis = 1)

array([160, 165, 206])

In [ ]:
# daywise min temperature
grid.min(axis = 0)

array([21, 24, 19, 21, 23, 25, 26])

In [107]:
grid.min(axis = 1)

array([19, 21, 27])

In [110]:
# get the position of maximum temperature across city for each day
print(grid.argmax(axis = 0))

[2 2 2 2 2 2 2]


## Random numbers
np.random.seed(...) fixes the starting point of the random sequence. Same seed, same "random" numbers, every time you rerun code

In [111]:
np.random.seed(42)

#### Shuffling and sampling: the core of a train/test split

In [112]:
np.random.seed(42)

In [ ]:
np.random.rand(4) # 4 floats

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
# this maintains distiribution with mean and sd
np.random.randn(4)

array([-0.23415337, -0.23413696,  1.57921282,  0.76743473])

In [115]:
np.random.randint(0, 20, size = 5)

array([ 1, 11,  5,  1,  0], dtype=int32)

In [116]:
temps

array([22, 24, 18, 21, 23, 25, 26])

In [117]:
np.random.shuffle(temps)

In [118]:
temps

array([25, 18, 22, 26, 23, 24, 21])

## np.where, argmax, argmin
np.where is a vectorized if/else

In [119]:
label = np.where(temps > 24, "warm", "cool")

In [120]:
label

array(['warm', 'cool', 'cool', 'warm', 'cool', 'cool', 'cool'],
      dtype='<U4')

## Transpose, stacking, cleanup

In [121]:
grid.shape

(3, 7)

In [122]:
grid.T

array([[22, 21, 28],
       [24, 24, 29],
       [19, 24, 27],
       [21, 21, 28],
       [23, 23, 31],
       [25, 25, 33],
       [26, 27, 30]])

In [123]:
grid.T.shape

(7, 3)

In [124]:
lalitpur = np.array([23,22,24,23,22,23,24])
lalitpur.shape

(7,)

In [125]:
np.vstack([grid,lalitpur])

array([[22, 24, 19, 21, 23, 25, 26],
       [21, 24, 24, 21, 23, 25, 27],
       [28, 29, 27, 28, 31, 33, 30],
       [23, 22, 24, 23, 22, 23, 24]])

In [126]:
np.vstack([grid,lalitpur]).shape

(4, 7)

#### Cleanup
.unique(cities)
.sort(temps)
.argsort(temps)
.isnan(temps)
np.nanmean(temps)